### ISSUE TITLE
Provide the training commands

### ISSUE THREAD

**Issue by Andrawzyf** [TAMU-VITA/ABD-Net#1]
HI，thanks for your awesome work，but can you Provide the training commands? thanks you very mush

**Comment by TianlongChenTAMU** [comment]
Thank you for asking.

https://github.com/TAMU-VITA/ABD-Net/blob/master/README_Training_Guides.md

Due to the limited space, I put training commands in a sperate readme. You can find it in the homepage or by this link. Sorry  for the inconvenient. I will highlight the remark.
