### ISSUE TITLE
some problems about finding the minimum eigenvalue

### ISSUE THREAD

**Issue by seanM29** [TAMU-VITA/ABD-Net#10]
I know that the inverse power method can find the minimum eigenvalue and equation (5) can find the maximum eigenvalue of X , 
but why the maximum eigenvalue of the **FF^T - lambda_1 I**
 is the minimum eignevalue of **FF^T** ? 
Besides in the code, it seems that you first use equation (5) get maximum eignevalue , and use **FF^T - lambda_1 I** to get the disancte between minimum and maximum eignevalue
Thank you for sharing results of your work.
This is a really impressive paper and your response is appreciated

**Comment by TianlongChenTAMU** [comment]
https://math.stackexchange.com/questions/271864/how-to-compute-the-smallest-eigenvalue-using-the-power-iteration-algorithm

Thank you for your question. I think you can find the detailed explaination through above link. Basicllay, A's smallest eigenvalue is the largest eigenvalue of B = A - lambda_A_max*I.

**Comment by seanM29** [comment]
Thank you so much!!
