### ISSUE TITLE
How do draw image with attenion?

### ISSUE THREAD

**Issue by sanduanji** [TAMU-VITA/ABD-Net#11]
Hello, i really enjoy you wonderfer work. Can you show how to draw colorful image with attenion weights? Just like those image in paper. Thx

**Comment by TianlongChenTAMU** [comment]
Hi! You can search Grad-CAM or RAM online. We also provide the related link in the paper.

**Comment by hsfzxjy** [comment]
Some of our visualization code are based on [this repo](https://github.com/utkuozbulak/pytorch-cnn-visualizations)

**Comment by xiyangzhuang** [comment]
you work,really deserves study and learning,  i wonder which layer's output was used? Just like your work in your paper. The results are poorer, as I use the fmap['intermediate'] directly, i think i missed something when reading your paper. Thanks for reply.
