### ISSUE TITLE
Why the evaluate results is changing sometimes? Anyone got the same problem like me?

### ISSUE THREAD

**Issue by xjiao004** [TAMU-VITA/ABD-Net#15]

**Comment by linyq17** [comment]
I got the same problem too.

**Comment by xjiao004** [comment]
Here is the answer: https://github.com/pytorch/pytorch/issues/7068。

> I got the same problem too.

**Comment by TomHeaven** [comment]
You might miss some parameters. See https://github.com/TAMU-VITA/ABD-Net/issues/21
