### ISSUE TITLE
pretrained model inference

### ISSUE THREAD

**Issue by dinara92** [TAMU-VITA/ABD-Net#16]
I want to perform inference with pretrained models on a custom dataset, to obtain features. Which part of the code is for single test image inference and feature extraction? (To then perform similarity test with another image's feature?)

Thanks for your great work!

**Comment by venkatesh-sakthivel** [comment]
Can someone tell us how this can be achieved ?

**Comment by wduo** [comment]
+1

**Comment by TianlongChenTAMU** [comment]
Hi, the testing part is referred to https://github.com/TAMU-VITA/ABD-Net/blob/master/README_Training_and_Testing_Guides.md.

I don't think it directly supports single image inference. Need to modify these https://github.com/TAMU-VITA/ABD-Net/blob/0fe343307678c9400827c03a7f22cde673e63f5c/train.py#L275.
