### ISSUE TITLE
About customized dataset

### ISSUE THREAD

**Issue by bywbilly** [TAMU-VITA/ABD-Net#17]
Hi,

Thanks for the awesome code. I am wondering what should I do if I want to train on my customized dataset. Do you have some suggestions? I guess I can follow the code within the dataset folder and write a similar one?

Thanks

**Comment by TianlongChenTAMU** [comment]
Thank you so much!

Yes, you are right, the most important thing is the data loader, you may need to follow the standard in our repo.
