### ISSUE TITLE
Why the evaluation will change while you evaluate the model at different time?Anyone knows what happened? PLEASE HELP!

### ISSUE THREAD

**Issue by xjiao004** [TAMU-VITA/ABD-Net#18]

**Comment by huijshang** [comment]
Yeah, I had the same problem.

**Comment by TomHeaven** [comment]
You missed some parameters. See https://github.com/TAMU-VITA/ABD-Net/issues/21

**Comment by xjiao004** [comment]
> You missed some parameters. See #21 
I also using flip-eval while evaluation. Did you notice the network changing sometime, these two parts below:
(1): GlobalBranch(
        (fc): Sequential(
          (0): Linear(in_features=960, out_features=1024, bias=True)
          (1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU(inplace)
          (3): Dropout(p=0.5)
        )
        (avgpool): AdaptiveAvgPool2d(output_size=1)
        (classifier): Linear(in_features=1024, out_features=333, bias=True)
      )
and
(sum_conv): Sequential(
          (0): Dropout2d(p=0.1)
          (1): Conv2d(1024, 1024, kernel_size=(1, 1), stride=(1, 1))
        )
        (avgpool): AdaptiveAvgPool2d(output_size=1)
        (classifiers): ModuleList(
          (0): Linear(in_features=1024, out_features=333, bias=True)
          (1): Linear(in_features=1024, out_features=333, bias=True)
        )
      )

**Comment by xjiao004** [comment]
> You missed some parameters. See #21

I also using flip-eval while evaluation. Did you notice the network changing sometime, these two parts below often exchange :
(1): GlobalBranch(
(fc): Sequential(
(0): Linear(in_features=960, out_features=1024, bias=True)
(1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
(2): ReLU(inplace)
(3): Dropout(p=0.5)
)
(avgpool): AdaptiveAvgPool2d(output_size=1)
(classifier): Linear(in_features=1024, out_features=333, bias=True)
)
and
(sum_conv): Sequential(
(0): Dropout2d(p=0.1)
(1): Conv2d(1024, 1024, kernel_size=(1, 1), stride=(1, 1))
)
(avgpool): AdaptiveAvgPool2d(output_size=1)
(classifiers): ModuleList(
(0): Linear(in_features=1024, out_features=333, bias=True)
(1): Linear(in_features=1024, out_features=333, bias=True)
)
)
