### ISSUE TITLE
the meanings of branches?

### ISSUE THREAD

**Issue by BrettLL** [TAMU-VITA/ABD-Net#19]
In branches , there are four sets [global, abd, dan, np].  Global and abd are default, but what is dan or np? I don't notice it in your paper, could you explain it for me, thank you !

**Comment by TianlongChenTAMU** [comment]
Hi,

DAN is the branch just use CAM/PAM attentions.

NP is the branch just evenly divided the feature map.

These two setting do not offer a better setting. Thus, we didn't include them in our paper.

Thank you!
