### ISSUE TITLE
Model zoo is not up-to-date

### ISSUE THREAD

**Issue by KaiyangZhou** [TAMU-VITA/ABD-Net#2]
Please see this https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO.html

**Comment by TianlongChenTAMU** [comment]
Thank you so much!
I have updated the MODEL ZOO link in my Readme. 

BTW, your code base is one of the best I have seen in my life. 👍🏻🙏

**Comment by KaiyangZhou** [comment]
Glad to hear that.

Your torchreid package is not an up-to-date one. There are several new features in the current torchreid, which you might be interested in.
