### ISSUE TITLE
run single method of  " baseline (XE) + O.F. "

### ISSUE THREAD

**Issue by tangsipeng** [TAMU-VITA/ABD-Net#22]
thanks for your great job !
in table 1 of the paper, i found that  " baseline (XE) + O.F. " Get a huge boost in both top-1 and mAP.
could you tell me  how to run that single method ? 

Method Market-1501 DukeMTMC
top1 mAP top1 mAP
baseline (XE) 91.50 77.40 82.80 66.40
baseline (XE) + PAM 92.10 78.10 83.80 67.00
baseline (XE) + CAM 91.80 78.00 84.30 67.60
baseline (XE) + PAM + CAM 92.70 78.50 84.40 67.90
baseline (XE) + O.F. 92.90 82.10 84.90 71.30
baseline (XE) + O.W. 92.50 78.50 83.70 67.40
baseline (XE) + O.F. + O.W. 93.20 82.30 85.30 72.20
baseline + SVD layer 90.80 76.90 79.40 62.50
ABD-Net (XE) 94.90 85.90 87.30 76.00
ABD-Net 95.60 88.28 89.00 78.59

**Comment by TianlongChenTAMU** [comment]
Thank you so much!

You can use this parameter --use-ow/--abd-dan to disable OW/attention. Then you will run the setting of "baseline(XE)+O.F."

More details are referred to https://github.com/TAMU-VITA/ABD-Net/blob/master/README_Training_and_Testing_Guides.md.
