### ISSUE TITLE
A bug which sometimes causes failure to resume training

### ISSUE THREAD

**Issue by Yogurt2019** [TAMU-VITA/ABD-Net#23]
at torchreid/components/branches.py class MultibranchNetwork at _get_branches
**branch_names = (frozenset(args['branches'])**
this sometimes can change the order of the branches, such as from abd, global to global, abd, causes the model sometimes cannot resume from checkpoint throwing exception like 
'Error loading checkpoint 
unexpected keys : ...'

**Comment by Cosmopal** [comment]
This is also causing the pretrained weighs to give different results, because in the weights provided, the branches are stored in a particular order

**Comment by Cosmopal** [comment]
A sorted list should do the trick

**Comment by Dtappledoghuati** [comment]
Hello, can I ask you some questions about training, my gpu
There seem to be some problems in this code, but I can't find it.
