### ISSUE TITLE
 python eval_acc.py error

### ISSUE THREAD

**Issue by 2448845600** [TAMU-VITA/ABD-Net#24]
Using Cython evaluation code as the backend
Traceback (most recent call last):
  File "eval_acc.py", line 29, in <module>
    from torchreid.losses.wrapped_cross_entropy_loss import WrappedCrossEntropyLoss
ModuleNotFoundError: No module named 'torchreid.losses.wrapped_cross_entropy_loss'

**Comment by TianlongChenTAMU** [comment]
Hi,

This module is provided by torchreid. You may need to run this first:

cd torchreid/eval_cylib
make

Thank you!

**Comment by young169** [comment]
> Hi,
> 
> This module is provided by torchreid. You may need to run this first:
> 
> cd torchreid/eval_cylib
> make
> 
> Thank you!

I still get the same error after make.
