### ISSUE TITLE
Is baseline(XE) training also using two-step transfer learning?

### ISSUE THREAD

**Issue by SpiritBear000** [TAMU-VITA/ABD-Net#25]
hi, Your work is awesome!  I have been doing some work recently, but the result of the baseline is very low. I see that your baseline (XE) has achieved a score of 91.5 / 77.4 on the market1501, Could you give me some guideance about the detail of your implement for baseline(XE). Following is my question.
1. After GAP, have you add any extra layer such as [fc512](https://github.com/layumi/Person_reID_baseline_pytorch/blob/6cbc2e6de7dbea526b23380c691938a9350a6b71/model.py#L29) before classifier.
2. Is baseline(XE) training also using two-step transfer learning?

Forgive me for not looking at your code in detail because I want to save time for deadlines

**Comment by TianlongChenTAMU** [comment]
Thank you!

For the first one, yes, I think so, we add an extra layer to obtain a stronger baseline.
For the second one, we don't use the two-step transfer learning. Just use the setting provides in our paper.
