### ISSUE TITLE
How did you visualize the attention map in two branches model？

### ISSUE THREAD

**Issue by ctrcv** [TAMU-VITA/ABD-Net#29]
Hi，could you tell how did you visualize the attention map in two branches model with Grad-CAM？As far as I know，Grad-CAM script in repo“pytorch-cnn-visualizations” can just visualize the
model with only one branch.

**Comment by Dtappledoghuati** [comment]
Hello, I would like to ask how many gpu-devices you use. I use a laptop to run the code, but I cannot set it to 0. I would like to ask your situation. Thanks.

**Comment by ctrcv** [comment]
Sorry， I have never trained the model， I just use it for testing performance in my pc with GTX1060(6GB)

**Comment by TianlongChenTAMU** [comment]
Hi, I will refer this method which is also adopted in our paper.

RAM visualization method from paper: Towards rich feature discovery with class activation maps augmentation for person re-identification.

This method is much simpler and effective.
