### ISSUE TITLE
About pretrained model file format

### ISSUE THREAD

**Issue by Lmy0217** [TAMU-VITA/ABD-Net#3]
The file format of the downloaded pretrained model is **tar**, but I got an error when I opened it with the compression software.
I opened the file in text form and found the `torch` word. So is the downloaded file in **pth** format, or did I make a mistake in downloading it?
```
downloaded file: market_final_best.pth.tar
md5: e306d943f6ddf837e5f5a619ccce8ee8
```

**Comment by TianlongChenTAMU** [comment]
Thank you for the question!

The md5 of your downloaded file is correct. 
BTW, you can load the .pth.tar file directly. I think this link maybe helpful.
https://stackoverflow.com/questions/51857274/how-can-i-load-and-use-a-pytorch-pth-tar-model

**Comment by Lmy0217** [comment]
It works, thanks for your help.
