### ISSUE TITLE
cannot import name 'BaseDataManager' from torchreid.data_manager

### ISSUE THREAD

**Issue by honglongcai** [TAMU-VITA/ABD-Net#4]
I met importerror when training the code.
![Screen Shot 2019-08-13 at 8 26 49 PM](https://user-images.githubusercontent.com/19878347/62992614-f15e0f80-be08-11e9-97c2-64b7cd6b02ae.png)
I think there is circular dependent imports in the code. I am wondering how to solve the issue.
Thanks!

**Comment by hsfzxjy** [comment]
Fixed. Thanks for feedback!

**Comment by honglongcai** [comment]
Thanks so much!
