### ISSUE TITLE
 I cannot reproduce by default parameters。

### ISSUE THREAD

**Issue by yuzhijun2** [TAMU-VITA/ABD-Net#5]
This result cannot be achieved. 
rank1=95.6
map=88.28
can you provide me the args.py file?

**Comment by TianlongChenTAMU** [comment]
Thank you for the question.

We have updated the README_Training_Guides.md. You can follow the setting in the doc and try again.

BTW, the fluctuation will be around 0.5 point.

**Comment by yuzhijun2** [comment]
Thank you so much!



---Original---
