### ISSUE TITLE
files can not find

### ISSUE THREAD

**Issue by ahuwangsheng** [TAMU-VITA/ABD-Net#6]
resnet_best.py
 from .tricks.feature_distilation import FeatureDistilationTrick
 from .tricks.attention import AttentionModule
 from .tricks.dropout import SimpleDropoutOptimizer
 but I cat not find it?

**Comment by hsfzxjy** [comment]
This file has been deprecated and I removed it just now.

ABD related files lie at `torchreid/models/resnet.py` and `torchreid/components/*`.
