### ISSUE TITLE
I cannot load your pre-trained model

### ISSUE THREAD

**Issue by changsn** [TAMU-VITA/ABD-Net#7]
I try to load the model "Market1501 best ABD-Net model" provided by you. However, I find the names and the number of parameters both are different from defined model. I hope you can help me. Thank you!

**Comment by hsfzxjy** [comment]
Oops, it's the model from our old codebase. We will fix it soon.

I just uploaded a [newly trained one](https://drive.google.com/file/d/13bvg8LUD7JinC-usAQyE2ys9zxo4P97e/view?usp=sharing) on Market-1501, with slight performance difference. Models on other datasets will come soon~

**Comment by hsfzxjy** [comment]
Oops, we just found that it's from our old codebase.
I've uploaded a [newly trained one](https://drive.google.com/open?id=13bvg8LUD7JinC-usAQyE2ys9zxo4P97e) for Market-1501, with slight performance difference compared with reported. The other models will be updated soon~
Thanks for feedback!

**Comment by changsn** [comment]
Hi, Thank you for your reply! Looking for your more progress in this field.

Xie Jingyi <notifications@github.com> 于2019年8月18日周日 下午3:25写道：
