### ISSUE TITLE
poor results

### ISSUE THREAD

**Issue by he010103** [TAMU-VITA/ABD-Net#9]
@hsfzxjy 
I use the command in the [our training guide](https://github.com/TAMU-VITA/ABD-Net/blob/master/README_Training_and_Testing_Guides.md)

> python train.py -s market1501 -t market1501 \
    --flip-eval --eval-freq 10 \
    --label-smooth \
    --criterion htri \
    --lambda-htri 0.1  \
    --data-augment crop,random-erase \
    --margin 1.2 \
    --train-batch-size 48 \
    --height 384 \
    --width 128 \
    --optim adam \
    --lr 0.0003 \
    --stepsize 20 40 \
    --gpu-devices 0,1 \
    --max-epoch 80 \
    --save-dir log \
    --arch resnet50 \
    --use-of \
    --abd-dan cam pam \
    --abd-np 2 \
    --shallow-cam \
    --use-ow

But after training, the performance is poor:
>Model size: 69.175 M
Loaded pretrained weights from 'log/checkpoint_ep80.pth.tar'
Evaluate only
Evaluating market1501 ...
Extracted features for query set, obtained 3368-by-3072 matrix
Extracted features for gallery set, obtained 15913-by-3072 matrix
==> BatchTime(s)/BatchSize(img): 0.190/100
Computing CMC and mAP
Results ----------
mAP: 72.77%
CMC curve
Rank-1  : 88.15%
Rank-5  : 95.01%
Rank-10 : 96.56%
Rank-20 : 97.71%
------------------

**Comment by hsfzxjy** [comment]
There should be no comma `,` in `--data-augment crop,random-erase`, and our training batch size is `64`. But I think there may be some other problems.
Would you please share the full training log? Just send it to my email hsfzxjy@gmail.com.

**Comment by he010103** [comment]
@hsfzxjy I use python3, torch1.1.0 with enough gpus(1080TI) in the training. I  found something wrong in the code:
1、if I use `--data-augment crop random-erase`, it will be wrong, so I have to use `--data-augment crop,random-erase`.
>Using Cython evaluation code as the backend
usage: train.py [-h] [--root ROOT] -s SOURCE_NAMES [SOURCE_NAMES ...] -t
                TARGET_NAMES [TARGET_NAMES ...] [-j WORKERS] [--height HEIGHT]
                [--width WIDTH] [--split-id SPLIT_ID]
                [--train-sampler TRAIN_SAMPLER]
                [--data-augment {none,crop,random-erase,color-jitter,crop,random-erase,crop,color-jitter,crop,color-jitter,random-erase}]
                [--seq-len SEQ_LEN] [--sample-method SAMPLE_METHOD]
                [--pool-tracklet-features {avg,max}] [--cuhk03-labeled]
                [--cuhk03-classic-split] [--use-metric-cuhk03] [--optim OPTIM]
                [--lr LR] [--weight-decay WEIGHT_DECAY] [--momentum MOMENTUM]
                [--sgd-dampening SGD_DAMPENING] [--sgd-nesterov]
                [--rmsprop-alpha RMSPROP_ALPHA] [--adam-beta1 ADAM_BETA1]
                [--adam-beta2 ADAM_BETA2] [--max-epoch MAX_EPOCH]
                [--start-epoch START_EPOCH]
                [--stepsize STEPSIZE [STEPSIZE ...]] [--gamma GAMMA]
                [--train-batch-size TRAIN_BATCH_SIZE]
                [--test-batch-size TEST_BATCH_SIZE] [--fixbase]
                [--fixbase-epoch FIXBASE_EPOCH]
                [--open-layers OPEN_LAYERS [OPEN_LAYERS ...]]
                [--criterion CRITERION] [--label-smooth] [--margin MARGIN]
                [--num-instances NUM_INSTANCES] [--htri-only]
                [--lambda-xent LAMBDA_XENT] [--lambda-htri LAMBDA_HTRI]
                [-a ARCH] [--load-weights LOAD_WEIGHTS] [--evaluate]
                [--eval-freq EVAL_FREQ] [--start-eval START_EVAL]
                [--flip-eval] [--print-freq PRINT_FREQ] [--seed SEED]
                [--resume PATH] [--save-dir SAVE_DIR] [--use-cpu]
                [--gpu-devices GPU_DEVICES] [--use-avai-gpus]
                [--visualize-ranks] [--compatibility]
                [--branches BRANCHES [BRANCHES ...]] [--dropout DROPOUT]
                [--global-dim GLOBAL_DIM] [--global-max-pooling]
                [--abd-dim ABD_DIM] [--abd-np ABD_NP]
                [--abd-dan ABD_DAN [ABD_DAN ...]] [--abd-dan-no-head]
                [--shallow-cam] [--np-dim NP_DIM] [--np-np NP_NP]
                [--np-with-global] [--np-max-pooling] [--dan-dim DAN_DIM]
                [--dan-dan DAN_DAN [DAN_DAN ...]] [--dan-dan-no-head]
                [--use-of] [--of-beta OF_BETA]
                [--of-start-epoch OF_START_EPOCH]
                [--of-position OF_POSITION [OF_POSITION ...]] [--use-ow]
                [--ow-beta OW_BETA]
train.py: error: unrecognized arguments: random-erase
2、When training in the 23 epoch，it will log:
>Using OF
Traceback (most recent call last):
  File "train.py", line 392, in <module>
    main()
  File "train.py", line 161, in main
    train(epoch, model, criterion, regularizer, optimizer, trainloader, use_gpu, fixbase=False)
  File "train.py", line 252, in train
    penalty = of_penalty(outputs)
  File "/mnt/lustrenvme/share/spring/envs/r0.2.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lustrenew/hezhiqun/experiments/Vehicle_Reid/ABD-Net/torchreid/losses/of_penalty.py", line 83, in forward
    singular_penalty = sum([self.apply_penalty(k, x) for k, x in feature_dict.items() if k in self.penalty_position])
  File "/mnt/lustrenew/hezhiqun/experiments/Vehicle_Reid/ABD-Net/torchreid/losses/of_penalty.py", line 83, in <listcomp>
    singular_penalty = sum([self.apply_penalty(k, x) for k, x in feature_dict.items() if k in self.penalty_position])
  File "/mnt/lustrenew/hezhiqun/experiments/Vehicle_Reid/ABD-Net/torchreid/losses/of_penalty.py", line 57, in apply_penalty
    return sum([self.apply_penalty(k, xx) for xx in x]) / len(x)
  File "/mnt/lustrenew/hezhiqun/experiments/Vehicle_Reid/ABD-Net/torchreid/losses/of_penalty.py", line 57, in <listcomp>
    return sum([self.apply_penalty(k, xx) for xx in x]) / len(x)
  File "/mnt/lustrenew/hezhiqun/experiments/Vehicle_Reid/ABD-Net/torchreid/losses/of_penalty.py", line 61, in apply_penalty
    smallest, largest = self.get_singular_values(W)
  File "/mnt/lustrenew/hezhiqun/experiments/Vehicle_Reid/ABD-Net/torchreid/losses/of_penalty.py", line 49, in get_singular_values
    tmp = self.dominant_eigenvalue(AAT - I)
RuntimeError: CUDA error: out of memory

So I use a smaller batch size(32 or 48), which lead to poor performance.

**Comment by hsfzxjy** [comment]
I fixed the `--data-augment` problem in the latest commit.

You might train the code again with `batch-size=32` and share the training log with me.

**Comment by honglongcai** [comment]
I met the same out of memory issue even though I used 4 1080Ti GPUs. I am wondering what happens at the 23rd epoch. Thanks

**Comment by TianlongChenTAMU** [comment]
It starts to calculate the O.F. regularization and it will require much more memory.
BTW, we mentioned our GPU setting in the paper. https://arxiv.org/abs/1908.01114

Thank you.

**Comment by he010103** [comment]
@hsfzxjy I found that without `--flip-eval`, the evaluation results will be different when I run again.
>python train.py -s market1501 -t market1501 \
    --eval-freq 10 \
    --label-smooth \
    --criterion htri \
    --lambda-htri 0.1  \
    --data-augment crop random-erase \
    --margin 1.2 \
    --train-batch-size 128 \
    --height 384 \
    --width 128 \
    --optim adam \
    --lr 0.0003 \
    --stepsize 20 40 \
    --gpu-devices 0,1 \
    --max-epoch 80 \
    --save-dir log \
    --arch resnet50 \
    --use-of \
    --abd-dan cam pam \
    --abd-np 2 \
    --shallow-cam \
    --use-ow \
    --evaluate \
    --load-weights log/checkpoint_ep50.pth.tar

The results will be 
>mAP: 67.62%
CMC curve
Rank-1  : 84.83%
Rank-5  : 93.23%
Rank-10 : 95.40%
Rank-20 : 97.00%

or 

>mAP: 48.24%
CMC curve
Rank-1  : 77.32%
Rank-5  : 89.04%
Rank-10 : 92.19%
Rank-20 : 94.24%

**Comment by Adorablepet** [comment]
@he010103 Your problem is actually caused by the inconsistency between the loading model and the model initialization.You can `print(model.state_dict().keys())` and `print(pretrain_dict.keys())`.You will find that when you have this problem, the printed keys are different.
my solution：In `branches.py` modfy `branch_names=['abd', 'global']`.You can try.
